name: R package tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        use-public-rspm: true

    - name: Install dependencies
      uses: r-lib/actions/setup-r-dependencies@v2
      with:
        extra-packages: any::covr
        needs: coverage

    - name: Check build
      run: |
        R CMD build .
        R CMD check didFF_*.tar.gz --as-cran

    - name: Check coverage
      run: |
        covr::package_coverage()
      shell: Rscript {0}

    - name: Show testthat output
      if: always()
      run: |
        ## --------------------------------------------------------------------
        find ${{ runner.temp }}/package -name 'testthat.Rout*' -exec cat '{}' \; || true
      shell: bash
